-- Adicione o ponto e vírgula antes da CTE, caso seja precedida por outra instrução
;WITH CTE_RASTREABILIDADE AS (
    -- Parte inicial: Começa com a OP especificada
    SELECT 
        1 AS [LEVEL],
        OP.DOCENTRY AS [N. OP],
        OP.ITEMCODE AS [CODIGO PAI],
        OP.PLANNEDQTY AS [QTD PLANEJADA],
        LINHA.ITEMCODE AS [CODIGO INSUMO],
        LINHA.DSCRIPTION AS [DESCRICAO],
        LINHA.QUANTITY AS [QUANTIDADE],
        LINHA.PRICE AS [CUSTO MEDIO],
        LINHA.QUANTITY * LINHA.PRICE AS [CUSTO],
        LOTE.BATCHNUM AS [LOTE],
        LINHA.LINENUM AS [LINHA OP],
        LOTE.BASELINNUM AS [LINHA LOTE],
        LOTE.BASETYPE
    FROM OWOR OP
    INNER JOIN IGE1 LINHA 
        ON LINHA.BASEREF = OP.DOCENTRY
    INNER JOIN IBT1 LOTE 
        ON LOTE.BASEENTRY = LINHA.DOCENTRY 
        AND LOTE.BASELINNUM = LINHA.LINENUM
    WHERE OP.DOCENTRY = @DocEntry

    UNION ALL

    -- Parte recursiva: Processa OPs baseadas em lotes com 4 caracteres
    SELECT 
        CTE_RASTREABILIDADE.[LEVEL] + 1 AS [LEVEL],
        OP.DOCENTRY AS [N. OP],
        OP.ITEMCODE AS [CODIGO PAI],
        OP.PLANNEDQTY AS [QTD PLANEJADA],
        LINHA.ITEMCODE AS [CODIGO INSUMO],
        LINHA.DSCRIPTION AS [DESCRICAO],
        LINHA.QUANTITY AS [QUANTIDADE],
        LINHA.PRICE AS [CUSTO MEDIO],
        LINHA.QUANTITY * LINHA.PRICE AS [CUSTO],
        LOTE.BATCHNUM AS [LOTE],
        LINHA.LINENUM AS [LINHA OP],
        LOTE.BASELINNUM AS [LINHA LOTE],
        LOTE.BASETYPE
    FROM CTE_RASTREABILIDADE
    INNER JOIN OWOR OP 
        ON OP.DOCENTRY = CAST(CTE_RASTREABILIDADE.[LOTE] AS INT)
    INNER JOIN IGE1 LINHA 
        ON LINHA.BASEREF = OP.DOCENTRY
    INNER JOIN IBT1 LOTE 
        ON LOTE.BASEENTRY = LINHA.DOCENTRY 
        AND LOTE.BASELINNUM = LINHA.LINENUM
    WHERE LEN(CTE_RASTREABILIDADE.[LOTE]) = 4
)

-- Consulta final
SELECT * 
FROM CTE_RASTREABILIDADE
ORDER BY [LEVEL], [N. OP];
