SELECT DISTINCT
    OP.DOCENTRY AS "N. OP",
    OP.ITEMCODE AS "CODIGO PAI",
    OP.PLANNEDQTY AS "QTD PLANEJADA",
    LINHA.ITEMCODE AS "CODIGO INSUMO",
    LINHA.DSCRIPTION AS "DESCRICAO",
    LINHA.QUANTITY AS "QUANTIDADE",
    LINHA.PRICE AS "CUSTO MEDIO",
    LINHA.QUANTITY * LINHA.PRICE AS "CUSTO",
    LOTE.BATCHNUM AS "LOTE",
    LINHA.LINENUM AS "LINHA OP",
    LOTE.BASELINNUM AS "LINHA LOTE",
    LOTE.BASETYPE
FROM OWOR OP
INNER JOIN IGE1 LINHA 
    ON LINHA.BASEREF = OP.DOCENTRY
LEFT JOIN IBT1 LOTE 
    ON LOTE.BASEENTRY = LINHA.DOCENTRY 
    AND LOTE.BASELINNUM = LINHA.LINENUM
WHERE 
    (LOTE.BASETYPE = 60 OR LOTE.BASETYPE IS NULL) 
    AND OP.DOCENTRY = 8971;
